name: generate-release-notes
description: |
  Generate release notes

  https://docs.github.com/en/rest/releases/releases#generate-release-notes-content-for-a-release
inputs:
  repository:
    description: owner/repository-name
    default: ${{ github.repository }}
  ref_name:
    description: ref_name
    default: ${{ github.ref_name }}
outputs:
  name:
    description: Release name
  body:
    description: Release body
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.repository }} ${{ inputs.ref_name }}
