changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
        - feat
        - feature

    - title: Bug Fixes
      labels:
        - bug
        - fix

    - title: Documentation
      labels:
        - documentation
        - docs

    - title: Breaking Changes
      labels:
        - breaking-change

    - title: Automation
      labels:
        - ci
        - cd
        - github-actions
        - automation

    - title: Other Changes
      labels:
        - "*"

    - title: Dependencies
      labels:
        - dependencies
