name: required/actionlint

on:
  pull_request:

env:
  # v1.6.23 https://github.com/rhysd/actionlint/releases
  SCRIPT_URL: https://raw.githubusercontent.com/rhysd/actionlint/51803be108613182daa27af760ae117916b53e3f/scripts/download-actionlint.bash
  REQUEST_URL: /repos/${{ github.repository }}/pulls/${{ github.event.number }}/files
  GH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

jobs:
  check_changes:
    runs-on: ubuntu-latest
    name: Check for changes
    outputs:
      changed: ${{ steps.check_changed_files.outputs.changed }}
    steps:
      - name: Check changed files
        id: check_changed_files
        run: |
          set -Eeuxo pipefail
          changed=$(
            gh api                                               \
              -H "Accept: application/vnd.github+json"           \
              "${REQUEST_URL}"                                   \
              | jq -r 'any(.[].filename; startswith(".github"))'
          )
          echo "changed=${changed}" >>"${GITHUB_OUTPUT}"

  lint_workflows:
    name: Lint workflows
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.changed == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Lint workflows
        run: |
          bash <(curl "${{ env.SCRIPT_URL }}")
          ./actionlint -color
