name: Actionlint

on:
  pull_request:

env:
  # v1.6.23 https://github.com/rhysd/actionlint/releases
  SCRIPT_URL: https://raw.githubusercontent.com/rhysd/actionlint/51803be108613182daa27af760ae117916b53e3f/scripts/download-actionlint.bash

jobs:
  actionlint:
    runs-on: ubuntu-latest
    name: Lint workflows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Lint workflows
        run: |
          workflows_changed=""
          for file in $(git diff --name-only HEAD^ HEAD); do
              echo "File changed: ${file}"
              [[ "${file}" == .github/* ]] || continue
              workflows_changed="true"
              break
          done
          [[ "${workflows_changed}" ]] || exit 0

          bash <(curl "${{ env.SCRIPT_URL }}")
          ./actionlint -color
