name: changelog-update

on:
  release:
    types: [released]
  workflow_call:

env:
  JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  update:
    name: Update CHANGELOG.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@bbfa2bd8afcc53bf7ec1f01e69a7847d82a8b4c6 # v1.6.2
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
        with:
          gpg_private_key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          author: ${{ steps.import_gpg.outputs.name }} <${{ steps.import_gpg.outputs.email }}>
          committer: ${{ steps.import_gpg.outputs.name }} <${{ steps.import_gpg.outputs.email }}>
          add-paths: CHANGELOG.md
          title: Add ${{ github.event.release.tag_name }} to CHANGELOG.md
          body: This PR was automatically generated in ${{ env.JOB_URL }}
          labels: chore, repo, size/m
          signoff: true
          branch: chore/changelog/add-version-${{ github.event.release.tag_name }}
          commit-message: |
            chore(changelog): add ${{ github.event.release.tag_name }}

            Job-url: ${{ env.JOB_URL }}

      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        run: |
          gh pr merge                                \
            --delete-branch                          \
            --merge                                  \
            --auto                                   \
            ${{ steps.pr.outputs.pull-request-url }}
