name: required/labeler-issue-triage
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    name: Add labels
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler-issue-triage.yml
