name: nightly

on:
  schedule:
    # daily at 23:00 UTC
    - cron: 0 23 * * *
  pull_request:

env:
  GH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

jobs:
  check_release:
    name: Check latest release
    runs-on: ubuntu-latest
    outputs:
      create_release: ${{ steps.check.outputs.create_release }}
      latest_release_version: ${{ steps.check.outputs.latest_release_version }}
      version: ${{ steps.check.outputs.version }}

    steps:
      - name: Check latest release
        id: check
        run: |
          create_release=true
          latest_gh_release=$(
            gh api                                              \
              -H "Accept: application/vnd.github+json"          \
              "/repos/${{ github.repository }}/releases/latest" \
              --jq .tag_name ||
                echo "0.1.0"
          )
          latest_tag=$(
            gh api                                     \
              -H "Accept: application/vnd.github+json" \
              "/repos/${{ github.repository }}/tags"   \
              --jq .[0].name
          )
          if [ "${latest_gh_release}" = "${latest_tag}" ]; then
            create_release=false
          fi

          {
            echo "create_release=${create_release}"
            echo "latest_release_version=${latest_gh_release}"
            echo "version=${latest_tag}"
          } >>"${GITHUB_OUTPUT}"

  release:
    name: Publish a release
    runs-on: ubuntu-latest
    needs: check_release
    if: needs.check_release.outputs.create_release == 'true'

    steps:
      - name: Create a release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.check_release.outputs.version }}
          generate_release_notes: true
