name: required / pr-title-lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@b6bca70dcd3e56e896605356ce09b76f7e1e0d39  # v5.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          requireScope: true
