name: release

on:
  schedule:
    # daily at 23:00 UTC
    - cron: 0 23 * * *
  workflow_dispatch:

jobs:
  release:
    name: reuse-release
    uses: ./.github/workflows/reuse-release.yml
    secrets: inherit
