name: release

on:
  push:
    tags:
      - v*

env:
  GH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

jobs:
  release:
    name: Create a release draft
    runs-on: ubuntu-latest

    steps:
      - name: Create a release draft
        run: |
          gh api                                     \
            --method POST                            \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases \
            -f tag_name='${{ github.ref_name }}'     \
          -F draft=true                              \
          -F generate_release_notes=true
