name: release

on:
  push:
    tags:
      - v*
  pull_request:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

jobs:
  release:
    name: Create a release draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate release notes
        id: notes
        uses: shishifubing/ci-actions-common/actions/generate-release-notes@feature/generate-release-notes
        with:
          ref_name: v0.1.17

      - name: Create a release draft
        run: |
          gh api                                      \
            --method POST                             \
            -H "Accept: application/vnd.github+json"  \
            /repos/${{ github.repository }}/releases  \
            -f tag_name='${{ github.ref_name }}'      \
            -F draft=true                             \
            -f name="${{ steps.notes.outputs.name }}" \
            -f body="${{ steps.notes.outputs.body }}"
