name: require-labeler-pr-triage

on:
  pull_request_target:

permissions:
  pull-requests: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  type:
    name: Add type labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
          configuration-path: .github/labeler-pr-triage.yml

  size:
    name: Add a size label
    runs-on: ubuntu-latest
    
    steps:
      - uses: CodelyTV/pr-size-labeler@54ef36785e9f4cb5ecf1949cfc9b00dbb621d761 # v1.8.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message_if_xl: ""
