name: require-labeler-pr-triage

on:
  pull_request_target:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

permissions:
  contents: read
  pull-requests: write

env:
  CONFIG_PATH: .github/labeler-pr-triage.yml

jobs:
  type:
    name: Add type labels
    runs-on: ubuntu-latest

    steps:
      - name: Check if config exists
        id: check
        run: |
          curl -fL "https://raw.githubusercontent.com/${{ github.repository }}/main/${{ env.CONFIG_PATH }}" \
            || echo "missing=true" >>"${GITHUB_OUTPUT}"
    
      - name: Add type labels
        if: steps.check.outputs.missing != 'true'
        uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
        with:
          sync-labels: true
          configuration-path: ${{ env.CONFIG_PATH }}

  size:
    name: Add a size label
    runs-on: ubuntu-latest
    
    steps:
      - name: Add a size label
        uses: CodelyTV/pr-size-labeler@54ef36785e9f4cb5ecf1949cfc9b00dbb621d761 # v1.8.1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          message_if_xl: ""
