name: reuse-release-info

on:
  workflow_call:
    outputs:
      name:
        description: release name
        value: ${{ jobs.info.outputs.name }}
      body:
        description: body of release notes
        value: ${{ jobs.info.outputs.body }}
      version:
        description: release version
        value: ${{ jobs.info.outputs.version }}
      last_version:
        description: last release version
        value: ${{ jobs.info.outputs.last_version }}
      create:
        description: whether there is a need to create a new release
        value: ${{ jobs.info.outputs.create }}

jobs:
  info:
    name: Get release info
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.info.outputs.name }}
      body: ${{ steps.info.outputs.body }}
      version: ${{ steps.info.outputs.version }}
      last_version: ${{ steps.info.outputs.last_version }}
      create: ${{ steps.info.outputs.create }}

    steps:
      - name: Get release info
        id: info
        uses: shishifubing/ci-actions-common/actions/release-info@main
        env:
          GH_TOKEN: ${{ github.token }}
