name: tag

on:
  push:
    branches:
      - main
  workflow_call:
    outputs:
      semVer:
        description: SemVer
        value: ${{ jobs.tag.outputs.semVer }}

env:
  BUILD_NUMBER: ${{ github.run_number }}
  JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  GITVERSION_CONFIG_URL: https://raw.githubusercontent.com/shishifubing/ci-actions-common/main/.github/GitVersion.yml

jobs:
  tag:
    name: Create a tag
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Download gitversion config
        run: |
          rm -rf GitVersion.yml
          wget "${GITVERSION_CONFIG_URL}"

      - name: Download gitversion
        uses: gittools/actions/gitversion/setup@31b3198b2de324472547fecec2c0f721b70c38e2 # v0.9.15
        with:
          versionSpec: 5.12.0

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@31b3198b2de324472547fecec2c0f721b70c38e2 # v0.9.15
        with:
          useConfigFile: true

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
        with:
          gpg_private_key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Tag
        env:
          GIT_AUTHOR_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import_gpg.outputs.email }}
        run: |
          tag="v${{ steps.gitversion.outputs.semVer }}"
          commits_count="${GITVERSION_COMMITSSINCEVERSIONSOURCE}"
          commits=$(git log -n "${commits_count}" --skip=1 --pretty='format:  - %H %s')

          # create the tag
          git tag                                               \
            -s                                                  \
            -a "${tag}"                                         \
            -m "Version ${{ steps.gitversion.outputs.semVer }}" \
            -m "‎"                                       \
            -m "Commits:"                                       \
            -m "${commits}"                                     \
            -m "Job-url: ${{ env.JOB_URL }}"                    \
            -m "‎"
          # verify the tag
          git tag -v "${tag}"
          # push the tag
          git push origin "${tag}"
